# Server - Render asigna el puerto dinamicamente
server.port=${PORT:8080}
server.address=0.0.0.0

# PostgreSQL - Render inyecta DATABASE_URL
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.h2.console.enabled=false

# CORS (produccion)
app.cors.allowed-origins=${ALLOWED_ORIGINS}

# Seguridad
spring.jpa.show-sql=false

